### ISSUE TITLE
Problemas con caracteres especiales

### ISSUE THREAD

**Issue by NicolasPL64** [Rubenmp/CAH_generator#4]
![image](https://github.com/Rubenmp/CAH_generator/assets/31411531/7ba1cefd-147c-4d0d-8316-4bb8f583b13b)

He estado mirando cómo intentar arreglarlo, pero no sé cómo funciona la codificación de texto.

**Comment by Rubenmp** [comment]
Gracias por reportarlo!

Acabo de probar (™ + ñ + © + á) y a mi me funciona (Ubuntu 22 con ficheros en UTF-8):

![image](https://github.com/Rubenmp/CAH_generator/assets/11651356/0a5bd292-d752-441e-89d7-f4747ae5ed7e)
He actualizado las dependencias [aquí](https://github.com/Rubenmp/CAH_generator/pull/5), no sé si eso lo resuelve o es problema concreto de Windows(?)

**Comment by NicolasPL64** [comment]
Vale, siguió sin funcionar si el .txt está en UTF-8, pero al cambiarlo a ANSI funcionó perfectamente.
![image](https://github.com/Rubenmp/CAH_generator/assets/31411531/e94a5dfa-5546-4310-9622-237110a548e3)

Voy a mirar si puedo hacer que el texto se alinee a la izquierda para que quede lo más parecido posible a las cartas originales. Necesito aprender a usar GitHub xD
Muchas gracias por el script! :D
